columnSuffix: null
contentColumnType: string
fieldGroup: 340e935e-a842-40c1-b3be-f0667d36f47a # Common
handle: accommodations
instructions: ''
name: Accommodations
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:b736fa2c-579c-42f8-8777-eb0a6a1e3852' # Accomodations
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
