contentColumnType: text
fieldGroup: 93181e72-df4b-4d19-aa48-41e97d5e3f82 # SEO
handle: descriptionTag
instructions: ''
name: 'Description Tag'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
