contentColumnType: string
fieldGroup: 340e935e-a842-40c1-b3be-f0667d36f47a # Common
handle: serviceIcon
instructions: ''
name: 'Service Icon'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Wifi
        -
          - value
          - wifi
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - TV
        -
          - value
          - television
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Cabin
        -
          - value
          - home
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Child
        -
          - value
          - child
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Shower
        -
          - value
          - shower
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bed-linen
        -
          - value
          - bed
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Dropdown
