enableVersioning: true
handle: links
name: Links
propagationMethod: all
siteSettings:
  d66411b8-3b8d-4763-9f8b-8f54c6ca6aef: # Gjerde-Camping NO
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
